### ISSUE TITLE
ERROR: LoadError: LoadError: UndefVarError: Device not defined

### ISSUE THREAD

**Issue by mirestrepo** [esproff/TopicModelsVB.jl#5]
This happens right after

```
 using TopicModelsVB
```

Do I need to set up an OpenCL Device?

**Comment by paulstey** [comment]
@mirestrepo, I was getting this same error message. The problem seems to be fixed on Master. I was on tagged version 0.0.1, but using `Pkg.checkout("TopicModelsVB")` fixed the issue for me.

**Comment by esproff** [comment]
Is this still a problem?
