### ISSUE TITLE
How to prepare docfile and lexfile?

### ISSUE THREAD

**Issue by grassdew** [esproff/TopicModelsVB.jl#6]
Hi,

Thanks for developing this amazing package. I have gone through the examples and have a quick question about data preparation. Is there a function within the package that can help users quickly prepare the docfile and lexfile for their own documents? Thanks in advance.

**Comment by ericproffitt** [comment]
If you mean from the raw text files then no.  It would be very difficult to design such a function which could anticipate all the possible formatting idiosyncrasies of raw text.

**Comment by grassdew** [comment]
Hi ericproffitt,

Thanks. I'm new to Julia and have trouble creating these files. Can you give me some suggestions on this? Also, are the terms in the lexfile required to be sorted in alphabetic order for the model fitting? Thank you.

**Comment by ericproffitt** [comment]
There really isn't any standard way to do it, except to slowly build a dictionary of keys to words based on those words in your text file.  As to the lexfile, no it's not required to be sorted in alphabetic order.

**Comment by grassdew** [comment]
Thank you.

**Comment by grassdew** [comment]
Hi ericproffitt,

I have created a docfile for my own dataset and tried to fit the LDA model on the corpus. Originally when I read in the corpus, it included 5 docs, but it became empty after I ran the command fixcorp!(corpus). How to deal with this issue?

**Comment by ericproffitt** [comment]
This is difficult to troubleshoot without seeing your docfile, is it small enough to copy-paste it in a comment?

**Comment by grassdew** [comment]
My docfile looks like this.
13,11,6
1,1,1
17,11,6
1,1,1
12,4,5,10,14,7,6,21
1,1,1,1,1,1,1,1
2,3,8,19,1,9,15,20,18,16
1,2,2,2,1,2,2,1,1,1
5,4
1,1

**Comment by ericproffitt** [comment]
because you don't include a lexfile when you read your corpus, you need to run padcorp!(corp) before you run fixcorp!(corp).  the padcorp! function basically produces a generic lex file based on your docfile (this is discussed in the tutorial).

Just be aware that your output won't be interpretable, since you never tell the model what words actually correspond to these keys.

**Comment by grassdew** [comment]
Actually, I have my lexfile, which looks like this:
1 capped
2 resides
3 extended
4 smoking
5 history
6 alcohol
7 significant
8 care
9 tracheostomy
10 believe
11 tobacco
12 patient
13 includes
14 heavy
15 tube
16 admission
17 denies
18 discharge
19 facility
20 unfortunately
21 past

But I got an error message after I run the following command.

corp = readcorp(;docfile="topic_modeling/lda/ldadocs.txt",
                lexfile="topic_modeling/lda/ldalex.txt",
                delim=',',counts=true,readers=false, ratings=false, stamps=false)
The error message shows: attempt to access 21*1 Array at index [Colon(),2].

**Comment by ericproffitt** [comment]
the lexfile needs to be tabbed spaced (I probably should have mentioned this in the tutorial), replace the spaces with tabs and you should be good just running:

readcorp(docfile=docfile, lexfile=lexfile)

**Comment by grassdew** [comment]
I tabbed spaced my lexfile, but I still get the error.
My lexfile now looks like this:
1   capped
2   resides
3   extended
4   smoking
5   history
6   alcohol
7   significant
8   care
9   tracheostomy
10  believe
11  tobacco
12  patient
13  includes
14  heavy
15  tube
16  admission
17  denies
18  discharge
19  facility
20  unfortunately
21  past

**Comment by grassdew** [comment]
It would be helpful to have this information in the tutorial. By the way, after I run the command: train!(lda, iter=150, tol=0.0), I get an error: ArgumentError: Dirichlet: alpha must be a positive vector.

**Comment by grassdew** [comment]
My script for LDA is as follows:
lda = LDA(corp, 3)
train!(lda, iter=50, tol=0.0)

I get the output:
topic 1     topic 2     topic 3
capped
2    capped
2    capped
2
Is there anything wrong with my specification of parameters or it's simply because my sample size is too small?

**Comment by ericproffitt** [comment]
That's strange that you're getting an error.  I just ran the following and I didn't get an error:

corp = readcorp(docfile=docfile_path, lexfile=lexfile_path, counts=true)
lda = LDA(corp, 3)
train!(lda, iter=150, tol=0.0)

These are the topics I got:

topic 1             topic 2              topic 3
tobacco          facility               history
alcohol            tube                  smoking
denies             tracheostomy   past
includes          care                   heavy
past                 extended           patient
unfortunately  unfortunately    believe
facility              discharge          significant
discharge        admission          alcohol
admission        resides              unfortunately
tube                 capped              facility
heavy               past                   discharge
patient             denies               denies
believe             heavy                admission
tracheostomy  includes            tube
care                  patient               includes

**Comment by grassdew** [comment]
I got an error when I ran: lda = LDA(corp,3). Below is the error message.

BoundsError: attempt to access 3×1 Array{Float64,2} at index [Colon(),[13,11,6]]
 in throw_boundserror(::Array{Float64,2}, ::Tuple{Colon,Array{Int64,1}}) at ./abstractarray.jl:363
 in checkbounds at ./abstractarray.jl:292 [inlined]
 in _getindex at ./multidimensional.jl:272 [inlined]
 in getindex at ./abstractarray.jl:760 [inlined]
 in Elogpw(::TopicModelsVB.LDA, ::Int64) at /Users/emily/.julia/v0.5/TopicModelsVB/src/LDA.jl:62
 in updateNewELBO!(::TopicModelsVB.LDA, ::Int64) at /Users/emily/.julia/v0.5/TopicModelsVB/src/LDA.jl:84
 in TopicModelsVB.LDA(::TopicModelsVB.Corpus, ::Int64) at /Users/emily/.julia/v0.5/TopicModelsVB/src/LDA.jl:41
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::String, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in (::Atom.##67#70)() at /Users/emily/.julia/v0.5/Atom/src/eval.jl:40
 in withpath(::Atom.##67#70, ::Void) at /Users/emily/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::Void) at /Users/emily/.julia/v0.5/Atom/src/eval.jl:46
 in macro expansion at /Users/emily/.julia/v0.5/Atom/src/eval.jl:109 [inlined]
 in (::Atom.##66#69)() at ./task.jl:60

**Comment by esproff** [comment]
when you enter:

```
corp
```

does it say you have 5 docs and 21 lex?

Also try entering
```
lda.beta
```

what is the dimension of that matrix?

**Comment by grassdew** [comment]
When I enter corp, it returns 5 docs and 1 lex. Guess that's why there is only one word in each topic.

**Comment by esproff** [comment]
There should be 21 lex, make sure your lex file is formatted correctly.  It should be plaintext, with tabs separating the keys from the words, with one key/word pair per line.

**Comment by grassdew** [comment]
I created my lexfile in Excel and save it as tab delimited text.
[ldalex.txt](https://github.com/esproff/TopicModelsVB.jl/files/966441/ldalex.txt)

**Comment by esproff** [comment]
Yah it's definitely Excel, Excel does all sorts of weird hidden formatting to files.  Just open up a plaintext editor and type your lexfile in there and it should work.

**Comment by grassdew** [comment]
I type the lexfile in a text editor, but it still doesn't work. The error appears right after I read the corpus.
BoundsError: attempt to access 1×1 Array{Any,2} at index [Colon(),2]
 in throw_boundserror(::Array{Any,2}, ::Tuple{Colon,Int64}) at ./abstractarray.jl:363
 in checkbounds at ./abstractarray.jl:292 [inlined]
 in _getindex at ./multidimensional.jl:272 [inlined]
 in getindex(::Array{Any,2}, ::Colon, ::Int64) at ./abstractarray.jl:760
 in #readcorp#17(::String, ::String, ::String, ::String, ::Char, ::Bool, ::Bool, ::Bool, ::Bool, ::TopicModelsVB.#readcorp) at /Users/emily/.julia/v0.5/TopicModelsVB/src/Corpus.jl:137
 in (::TopicModelsVB.#kw##readcorp)(::Array{Any,1}, ::TopicModelsVB.#readcorp) at ./<missing>:0
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::String, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in (::Atom.##67#70)() at /Users/emily/.julia/v0.5/Atom/src/eval.jl:40
 in withpath(::Atom.##67#70, ::Void) at /Users/emily/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::Void) at /Users/emily/.julia/v0.5/Atom/src/eval.jl:46
 in macro expansion at /Users/emily/.julia/v0.5/Atom/src/eval.jl:109 [inlined]
 in (::Atom.##66#69)() at ./task.jl:60

**Comment by esproff** [comment]
It's still a formatting issue with the file then, including hidden string literals, each line should be of the form:

(integer key)\t(word)\n

Are you on a windows machine or linux/macos?

**Comment by grassdew** [comment]
I'm using Atom(text editor) on a mac.

**Comment by esproff** [comment]
It's still a formatting issue with the file then, it's not the package.  Take a look at your ldalex file:

```
ldalex = readdlm(ldalex_path)
ldalex[1]
```

You get:
`"\U3cbbe1c0c\0a\0p\0p\0e\0d\0"`

So clearly there's some funky formatting going on.

**Comment by grassdew** [comment]
I got the following.

ldalex = readdlm(ldalex_path).
1×43 Array{Any,2}:
 1  "capped"  2  "resides"  3  …  20  "unfortunately"  21  "past"  ""
ldalex[1]
1

**Comment by esproff** [comment]
What I posted was for the Excel version you sent me.  But as you can see with the one you posted from Atom, it's not right.  The words shouldn't have quotes, the array should be 21x2 rather than 1x43.  Clearly the file is not formatted correctly.

Open up textedit, choose the Make Plain Text option in the Format menu, and then type it in there, and it should work.

**Comment by esproff** [comment]
Oops, I guess Julia shows them with quotes, so it's just the newline characters (\n) which you're missing.

**Comment by grassdew** [comment]
When I typed them up, I use the Enter key.

**Comment by grassdew** [comment]
Finally it works!

**Comment by esproff** [comment]
Yah when writing up text from scratch to be used programmatically, unless you are going for a specific file format, you should always make it plain unicode text I think (not an expert on this).  Otherwise you get all sorts of crazy hidden formatting occurring in the text file.

**Comment by grassdew** [comment]
Thanks for your help. I will take your advice.
