### ISSUE TITLE
probability distribution of topics and number of keywords within topics

### ISSUE THREAD

**Issue by grassdew** [esproff/TopicModelsVB.jl#9]
Hi,

The lda.gamma command returns a vector of weights of topics for a document. Can I get a probability distribution of topics instead? Also, can I specify the number of keywords within each topic in the showtopics command? Thank you.

**Comment by esproff** [comment]
`lda.gamma[m]` is the parameter for a Dirichlet distribution, so you can get the _expected_ probability distribution of topics for a particular document `m` by simply normalizing that vector.

Each topic is a probability distribution over the entire lexicon, to see the top 20 words for example, simply write `showtopics(model, 20)`.

**Comment by grassdew** [comment]
Thanks.
